<?xml version="1.0" encoding="utf-8"?><Database Name="BallersDraft" Class="BallersDraftDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=EUCLID;Initial Catalog=BallersDraft;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BallersDraftConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChatRoom" Member="ChatRooms">
    <Type Name="ChatRoom">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="User_ChatRoom" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DraftMoves" Member="DraftMoves">
    <Type Name="DraftMove">
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SeasonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Round" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pick" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoveType" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlayerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DraftOrder_DraftMove" Member="DraftOrder" ThisKey="SeasonID,Pick" OtherKey="SeasonID,Order" Type="DraftOrder" IsForeignKey="true" />
      <Association Name="Player_DraftMove" Member="Player" ThisKey="PlayerID" OtherKey="PlayerID" Type="Player" IsForeignKey="true" />
      <Association Name="User_DraftMove" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DraftOrder" Member="DraftOrders">
    <Type Name="DraftOrder">
      <Column Name="SeasonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DraftOrder_DraftMove" Member="DraftMoves" ThisKey="SeasonID,Order" OtherKey="SeasonID,Pick" Type="DraftMove" />
      <Association Name="User_DraftOrder" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DraftStatus" Member="DraftStatus">
    <Type Name="DraftStatus">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Players" Member="Players">
    <Type Name="Player">
      <Column Name="PlayerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Suffix" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Identifier" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Team" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Player_DraftMove" Member="DraftMoves" ThisKey="PlayerID" OtherKey="PlayerID" Type="DraftMove" />
    </Type>
  </Table>
  <Table Name="dbo.Usernames" Member="Usernames">
    <Type Name="Username">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Member="Username1" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TeamName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Username" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DraftOverrides" Member="DraftOverrides">
    <Type Name="DraftOverride">
      <Column Name="SeasonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Round" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pick" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_DraftOverride" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserStatus" Member="UserStatus">
    <Type Name="UserStatus">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SeasonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Queue" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="User_UserStatus" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_ChatRoom" Member="ChatRooms" ThisKey="UserID" OtherKey="UserID" Type="ChatRoom" />
      <Association Name="User_DraftMove" Member="DraftMoves" ThisKey="UserID" OtherKey="UserID" Type="DraftMove" />
      <Association Name="User_DraftOrder" Member="DraftOrders" ThisKey="UserID" OtherKey="UserID" Type="DraftOrder" />
      <Association Name="User_Username" Member="Usernames" ThisKey="UserID" OtherKey="UserID" Type="Username" />
      <Association Name="User_DraftOverride" Member="DraftOverrides" ThisKey="UserID" OtherKey="UserID" Type="DraftOverride" />
      <Association Name="User_UserStatus" Member="UserStatus" ThisKey="UserID" OtherKey="UserID" Type="UserStatus" />
    </Type>
  </Table>
</Database>